// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct Conv1DVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kConv1DVariantCount = 2;
inline constexpr int kConv1DDefaultVariant = 0;

inline constexpr Conv1DVariantInfo kConv1DVariants[kConv1DVariantCount] = {
    {"Conv1DNaive", 256, 1, 256, 1, "Naive (global memory)"},
    {"Conv1DTiled", 256, 1, 256, 1, "SharedMem input tiled"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledConv1DNaive(DataType datatype);
std::optional<std::vector<uint32_t>> compiledConv1DTiled(DataType datatype);

using CompiledConv1DFn = std::optional<std::vector<uint32_t>> (*)(DataType);

inline const CompiledConv1DFn kConv1DCompiledFns[kConv1DVariantCount] = {
    compiledConv1DNaive,
    compiledConv1DTiled,
};

/// Returns compiled SPIR-V for a conv1d variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledConv1D(int variantIndex, DataType datatype = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kConv1DVariantCount)
        return std::nullopt;
    return kConv1DCompiledFns[variantIndex](datatype);
}

/// Returns the number of conv1d variants.
inline int getConv1DVariantCount() {
    return kConv1DVariantCount;
}

/// Returns the name of a conv1d variant by index.
inline const char* getConv1DVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kConv1DVariantCount)
        return "Unknown";
    return kConv1DVariants[variantIndex].name;
}

} // namespace cut
