// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <optional>
#include <vector>

namespace cut {

std::optional<std::vector<uint32_t>> compiledCopy(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledTranspose(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledPad(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledEmbedding(DataType datatype = DataType::Float32);

} // namespace cut
