// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <optional>
#include <vector>

namespace cut {

std::optional<std::vector<uint32_t>> compiledScanPerWg(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledScanPartialSums(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledScanPropagate(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledScanUint(DataType datatype = DataType::Float32);

} // namespace cut
