// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct ScanVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kScanVariantCount = 24;
inline constexpr int kScanDefaultVariant = 19;

inline constexpr ScanVariantInfo kScanVariants[kScanVariantCount] = {
    {"ScanIPT8", 256, 1, 256, 8, "Decoupled look-back scan, 8 items/thread"},
    {"ScanIPT12", 256, 1, 256, 12, "Decoupled look-back scan, 12 items/thread (4-aligned: VECW=4 shared access, conflict-free unpadded)"},
    {"ScanIPT14", 256, 1, 256, 14, "Decoupled look-back scan, 14 items/thread"},
    {"ScanIPT16", 256, 1, 256, 16, "Decoupled look-back scan, 16 items/thread"},
    {"ScanIPT18", 256, 1, 256, 18, "Decoupled look-back scan, 18 items/thread"},
    {"ScanIPT20", 256, 1, 256, 20, "Decoupled look-back scan, 20 items/thread (4-aligned: VECW=4 shared access, conflict-free unpadded)"},
    {"ScanIPT22", 256, 1, 256, 22, "Decoupled look-back scan, 22 items/thread"},
    {"ScanIPT24", 256, 1, 256, 24, "Decoupled look-back scan, 24 items/thread"},
    {"ScanIPT28", 256, 1, 256, 28, "Decoupled look-back scan, 28 items/thread (4-aligned: VECW=4 shared access, conflict-free unpadded)"},
    {"ScanIPT32", 256, 1, 256, 32, "Decoupled look-back scan, 32 items/thread"},
    {"ScanIPT36", 256, 1, 256, 36, "Decoupled look-back scan, 36 items/thread (4-aligned: VECW=4 shared access, conflict-free unpadded)"},
    {"ScanIPT40", 256, 1, 256, 40, "Decoupled look-back scan, 40 items/thread"},
    {"ScanIPT44", 256, 1, 256, 44, "Decoupled look-back scan, 44 items/thread (4-aligned: VECW=4 shared access, conflict-free unpadded)"},
    {"ScanIPT46", 256, 1, 256, 46, "Decoupled look-back scan, 46 items/thread (48KB-shared peak)"},
    {"ScanRegIPT8", 256, 1, 256, 8, "Register-resident decoupled scan, 8 items/thread"},
    {"ScanWTIPT10", 256, 1, 256, 10, "Decoupled look-back scan, 10 items/thread, warp-transposed to a blocked scan (even: 2-way bank conflict on the blocked read)"},
    {"ScanWTIPT11", 256, 1, 256, 11, "Decoupled look-back scan, 11 items/thread, warp-transposed to a blocked scan (odd: conflict-free blocked read)"},
    {"ScanWTIPT12", 256, 1, 256, 12, "Decoupled look-back scan, 12 items/thread, warp-transposed to a blocked scan (even: 4-way bank conflict on the blocked read)"},
    {"ScanWTIPT13", 256, 1, 256, 13, "Decoupled look-back scan, 13 items/thread, warp-transposed to a blocked scan (odd: conflict-free blocked read)"},
    {"ScanWTIPT14", 256, 1, 256, 14, "Decoupled look-back scan, 14 items/thread, warp-transposed to a blocked scan (even: 2-way bank conflict on the blocked read, control for IPT13/15)"},
    {"ScanWTIPT15", 256, 1, 256, 15, "Decoupled look-back scan, 15 items/thread, warp-transposed to a blocked scan (odd: conflict-free blocked read, CUB's f32 policy)"},
    {"ScanWTIPT18", 256, 1, 256, 18, "Decoupled look-back scan, 18 items/thread, warp-transposed to a blocked scan (even: 2-way bank conflict on the blocked read)"},
    {"ScanWTIPT20", 256, 1, 256, 20, "Decoupled look-back scan, 20 items/thread, warp-transposed to a blocked scan (even: 4-way bank conflict on the blocked read)"},
    {"ScanWTIPT26", 256, 1, 256, 26, "Decoupled look-back scan, 26 items/thread, warp-transposed to a blocked scan (even: 2-way bank conflict on the blocked read)"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledScanIPT8(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT12(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT14(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT18(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT20(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT22(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT24(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT28(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT32(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT36(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT40(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT44(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT46(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanRegIPT8(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT10(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT11(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT12(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT13(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT14(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT15(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT18(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT20(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT26(DataType input, DataType output);

using CompiledScanFn = std::optional<std::vector<uint32_t>> (*)(DataType, DataType);

inline const CompiledScanFn kScanCompiledFns[kScanVariantCount] = {
    compiledScanIPT8,
    compiledScanIPT12,
    compiledScanIPT14,
    compiledScanIPT16,
    compiledScanIPT18,
    compiledScanIPT20,
    compiledScanIPT22,
    compiledScanIPT24,
    compiledScanIPT28,
    compiledScanIPT32,
    compiledScanIPT36,
    compiledScanIPT40,
    compiledScanIPT44,
    compiledScanIPT46,
    compiledScanRegIPT8,
    compiledScanWTIPT10,
    compiledScanWTIPT11,
    compiledScanWTIPT12,
    compiledScanWTIPT13,
    compiledScanWTIPT14,
    compiledScanWTIPT15,
    compiledScanWTIPT18,
    compiledScanWTIPT20,
    compiledScanWTIPT26,
};

/// Returns compiled SPIR-V for a scan variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledScan(int variantIndex, DataType input = DataType::Float32, DataType output = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kScanVariantCount)
        return std::nullopt;
    return kScanCompiledFns[variantIndex](input, output);
}

/// Returns the number of scan variants.
inline int getScanVariantCount() {
    return kScanVariantCount;
}

/// Returns the name of a scan variant by index.
inline const char* getScanVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kScanVariantCount)
        return "Unknown";
    return kScanVariants[variantIndex].name;
}

} // namespace cut
