// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <optional>
#include <vector>

namespace cut {

std::optional<std::vector<uint32_t>> compiledScanPerWg(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanPartialSums(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanPropagate(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanUint(DataType input, DataType output);

} // namespace cut
