// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct ScanVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kScanVariantCount = 55;
inline constexpr int kScanDefaultVariant = 46;

inline constexpr ScanVariantInfo kScanVariants[kScanVariantCount] = {
    {"ScanIPT8", 256, 1, 256, 8, "Decoupled look-back scan, 8 items/thread"},
    {"ScanIPT12", 256, 1, 256, 12, "Decoupled look-back scan, 12 items/thread (4-aligned: VECW=4 shared access, conflict-free unpadded)"},
    {"ScanIPT14", 256, 1, 256, 14, "Decoupled look-back scan, 14 items/thread"},
    {"ScanIPT16", 256, 1, 256, 16, "Decoupled look-back scan, 16 items/thread"},
    {"ScanIPT18", 256, 1, 256, 18, "Decoupled look-back scan, 18 items/thread"},
    {"ScanIPT20", 256, 1, 256, 20, "Decoupled look-back scan, 20 items/thread (4-aligned: VECW=4 shared access, conflict-free unpadded)"},
    {"ScanIPT22", 256, 1, 256, 22, "Decoupled look-back scan, 22 items/thread"},
    {"ScanIPT24", 256, 1, 256, 24, "Decoupled look-back scan, 24 items/thread"},
    {"ScanIPT28", 256, 1, 256, 28, "Decoupled look-back scan, 28 items/thread (4-aligned: VECW=4 shared access, conflict-free unpadded)"},
    {"ScanIPT32", 256, 1, 256, 32, "Decoupled look-back scan, 32 items/thread"},
    {"ScanIPT36", 256, 1, 256, 36, "Decoupled look-back scan, 36 items/thread (4-aligned: VECW=4 shared access, conflict-free unpadded)"},
    {"ScanIPT40", 256, 1, 256, 40, "Decoupled look-back scan, 40 items/thread"},
    {"ScanIPT44", 256, 1, 256, 44, "Decoupled look-back scan, 44 items/thread (4-aligned: VECW=4 shared access, conflict-free unpadded)"},
    {"ScanIPT46", 256, 1, 256, 46, "Decoupled look-back scan, 46 items/thread (48KB-shared peak)"},
    {"ScanRegIPT8", 256, 1, 256, 8, "Register-resident decoupled scan, 8 items/thread"},
    {"ScanRegIPT16", 256, 1, 256, 16, "Register-resident decoupled scan, 16 items/thread"},
    {"ScanRegIPT24", 256, 1, 256, 24, "Register-resident decoupled scan, 24 items/thread"},
    {"ScanRegIPT32", 256, 1, 256, 32, "Register-resident decoupled scan, 32 items/thread"},
    {"ScanRegIPT40", 256, 1, 256, 40, "Register-resident decoupled scan, 40 items/thread"},
    {"ScanRegIPT48", 256, 1, 256, 48, "Register-resident decoupled scan, 48 items/thread (past the 48KB-shared ceiling)"},
    {"ScanRegIPT64", 256, 1, 256, 64, "Register-resident decoupled scan, 64 items/thread (past the 48KB-shared ceiling)"},
    {"ScanXchgW1IPT16", 256, 1, 256, 16, "Windowed-exchange decoupled scan, 16 items/thread, 1 warp/round (2.1KB window vs 16KB full tile)"},
    {"ScanXchgW1IPT32", 256, 1, 256, 32, "Windowed-exchange decoupled scan, 32 items/thread, 1 warp/round (4.1KB window vs 32KB full tile)"},
    {"ScanXchgW1IPT48", 256, 1, 256, 48, "Windowed-exchange decoupled scan, 48 items/thread, 1 warp/round (6.1KB window vs 48KB full tile)"},
    {"ScanXchgW1IPT64", 256, 1, 256, 64, "Windowed-exchange decoupled scan, 64 items/thread, 1 warp/round (8.1KB window vs 64KB full tile)"},
    {"ScanXchgW2IPT16", 256, 1, 256, 16, "Windowed-exchange decoupled scan, 16 items/thread, 2 warps/round (4.2KB window vs 16KB full tile)"},
    {"ScanXchgW2IPT32", 256, 1, 256, 32, "Windowed-exchange decoupled scan, 32 items/thread, 2 warps/round (8.2KB window vs 32KB full tile)"},
    {"ScanXchgW2IPT48", 256, 1, 256, 48, "Windowed-exchange decoupled scan, 48 items/thread, 2 warps/round (12.2KB window vs 48KB full tile)"},
    {"ScanXchgW2IPT64", 256, 1, 256, 64, "Windowed-exchange decoupled scan, 64 items/thread, 2 warps/round (16.2KB window vs 64KB full tile)"},
    {"ScanXchgW4IPT16", 256, 1, 256, 16, "Windowed-exchange decoupled scan, 16 items/thread, 4 warps/round (8.5KB window, 2 rounds)"},
    {"ScanXchgW4IPT32", 256, 1, 256, 32, "Windowed-exchange decoupled scan, 32 items/thread, 4 warps/round (16.5KB window, 2 rounds)"},
    {"ScanXchgW4IPT48", 256, 1, 256, 48, "Windowed-exchange decoupled scan, 48 items/thread, 4 warps/round (24.5KB window, 2 rounds)"},
    {"ScanXchgW4IPT64", 256, 1, 256, 64, "Windowed-exchange decoupled scan, 64 items/thread, 4 warps/round (32.5KB window, 2 rounds)"},
    {"ScanXchgW8IPT16", 256, 1, 256, 16, "Windowed-exchange decoupled scan, 16 items/thread, 8 warps/round (17.0KB window, no time-slicing, one region per warp)"},
    {"ScanXchgW8IPT32", 256, 1, 256, 32, "Windowed-exchange decoupled scan, 32 items/thread, 8 warps/round (33.0KB window, no time-slicing, one region per warp)"},
    {"ScanXchgW4B512IPT16", 512, 1, 512, 16, "Windowed-exchange decoupled scan, 512 threads/group, 16 items/thread, 4 warps/round (8.5KB window)"},
    {"ScanXchgW8B512IPT16", 512, 1, 512, 16, "Windowed-exchange decoupled scan, 512 threads/group, 16 items/thread, 8 warps/round (17.0KB window)"},
    {"ScanXchgW4B512IPT32", 512, 1, 512, 32, "Windowed-exchange decoupled scan, 512 threads/group, 32 items/thread, 4 warps/round (16.5KB window)"},
    {"ScanXchgW16B512IPT16", 512, 1, 512, 16, "Windowed-exchange decoupled scan, 512 threads/group, 16 items/thread, 16 warps/round (34.0KB window)"},
    {"ScanXchgW8B1024IPT16", 1024, 1, 1024, 16, "Windowed-exchange decoupled scan, 1024 threads/group, 16 items/thread, 8 warps/round (17.0KB window)"},
    {"ScanXchgW16B1024IPT16", 1024, 1, 1024, 16, "Windowed-exchange decoupled scan, 1024 threads/group, 16 items/thread, 16 warps/round (34.0KB window)"},
    {"ScanWTIPT11", 256, 1, 256, 11, "Decoupled look-back scan, 11 items/thread, warp-transposed to a blocked scan (odd: conflict-free blocked read)"},
    {"ScanWTIPT13", 256, 1, 256, 13, "Decoupled look-back scan, 13 items/thread, warp-transposed to a blocked scan (odd: conflict-free blocked read)"},
    {"ScanWTIPT15", 256, 1, 256, 15, "Decoupled look-back scan, 15 items/thread, warp-transposed to a blocked scan (odd: conflict-free blocked read, CUB's f32 policy)"},
    {"ScanWTIPT17", 256, 1, 256, 17, "Decoupled look-back scan, 17 items/thread, warp-transposed to a blocked scan (odd: conflict-free blocked read)"},
    {"ScanWTIPT21", 256, 1, 256, 21, "Decoupled look-back scan, 21 items/thread, warp-transposed to a blocked scan (odd: conflict-free blocked read)"},
    {"ScanWTIPT14", 256, 1, 256, 14, "Decoupled look-back scan, 14 items/thread, warp-transposed to a blocked scan (even: 2-way bank conflict on the blocked read, control for IPT13/15)"},
    {"ScanWTIPT16", 256, 1, 256, 16, "Decoupled look-back scan, 16 items/thread, warp-transposed to a blocked scan (power of two: 16-way bank conflict on the blocked read, worst-case control)"},
    {"ScanWTIPT10", 256, 1, 256, 10, "Decoupled look-back scan, 10 items/thread, warp-transposed to a blocked scan (even: 2-way bank conflict on the blocked read)"},
    {"ScanWTIPT12", 256, 1, 256, 12, "Decoupled look-back scan, 12 items/thread, warp-transposed to a blocked scan (even: 4-way bank conflict on the blocked read)"},
    {"ScanWTIPT18", 256, 1, 256, 18, "Decoupled look-back scan, 18 items/thread, warp-transposed to a blocked scan (even: 2-way bank conflict on the blocked read)"},
    {"ScanWTIPT20", 256, 1, 256, 20, "Decoupled look-back scan, 20 items/thread, warp-transposed to a blocked scan (even: 4-way bank conflict on the blocked read)"},
    {"ScanWTIPT22", 256, 1, 256, 22, "Decoupled look-back scan, 22 items/thread, warp-transposed to a blocked scan (even: 2-way bank conflict on the blocked read)"},
    {"ScanWTIPT24", 256, 1, 256, 24, "Decoupled look-back scan, 24 items/thread, warp-transposed to a blocked scan (even: 8-way bank conflict on the blocked read)"},
    {"ScanWTIPT26", 256, 1, 256, 26, "Decoupled look-back scan, 26 items/thread, warp-transposed to a blocked scan (even: 2-way bank conflict on the blocked read)"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledScanIPT8(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT12(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT14(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT18(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT20(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT22(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT24(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT28(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT32(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT36(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT40(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT44(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanIPT46(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanRegIPT8(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanRegIPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanRegIPT24(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanRegIPT32(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanRegIPT40(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanRegIPT48(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanRegIPT64(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW1IPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW1IPT32(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW1IPT48(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW1IPT64(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW2IPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW2IPT32(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW2IPT48(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW2IPT64(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW4IPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW4IPT32(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW4IPT48(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW4IPT64(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW8IPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW8IPT32(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW4B512IPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW8B512IPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW4B512IPT32(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW16B512IPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW8B1024IPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanXchgW16B1024IPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT11(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT13(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT15(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT17(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT21(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT14(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT10(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT12(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT18(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT20(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT22(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT24(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledScanWTIPT26(DataType input, DataType output);

using CompiledScanFn = std::optional<std::vector<uint32_t>> (*)(DataType, DataType);

inline const CompiledScanFn kScanCompiledFns[kScanVariantCount] = {
    compiledScanIPT8,
    compiledScanIPT12,
    compiledScanIPT14,
    compiledScanIPT16,
    compiledScanIPT18,
    compiledScanIPT20,
    compiledScanIPT22,
    compiledScanIPT24,
    compiledScanIPT28,
    compiledScanIPT32,
    compiledScanIPT36,
    compiledScanIPT40,
    compiledScanIPT44,
    compiledScanIPT46,
    compiledScanRegIPT8,
    compiledScanRegIPT16,
    compiledScanRegIPT24,
    compiledScanRegIPT32,
    compiledScanRegIPT40,
    compiledScanRegIPT48,
    compiledScanRegIPT64,
    compiledScanXchgW1IPT16,
    compiledScanXchgW1IPT32,
    compiledScanXchgW1IPT48,
    compiledScanXchgW1IPT64,
    compiledScanXchgW2IPT16,
    compiledScanXchgW2IPT32,
    compiledScanXchgW2IPT48,
    compiledScanXchgW2IPT64,
    compiledScanXchgW4IPT16,
    compiledScanXchgW4IPT32,
    compiledScanXchgW4IPT48,
    compiledScanXchgW4IPT64,
    compiledScanXchgW8IPT16,
    compiledScanXchgW8IPT32,
    compiledScanXchgW4B512IPT16,
    compiledScanXchgW8B512IPT16,
    compiledScanXchgW4B512IPT32,
    compiledScanXchgW16B512IPT16,
    compiledScanXchgW8B1024IPT16,
    compiledScanXchgW16B1024IPT16,
    compiledScanWTIPT11,
    compiledScanWTIPT13,
    compiledScanWTIPT15,
    compiledScanWTIPT17,
    compiledScanWTIPT21,
    compiledScanWTIPT14,
    compiledScanWTIPT16,
    compiledScanWTIPT10,
    compiledScanWTIPT12,
    compiledScanWTIPT18,
    compiledScanWTIPT20,
    compiledScanWTIPT22,
    compiledScanWTIPT24,
    compiledScanWTIPT26,
};

/// Returns compiled SPIR-V for a scan variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledScan(int variantIndex, DataType input = DataType::Float32, DataType output = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kScanVariantCount)
        return std::nullopt;
    return kScanCompiledFns[variantIndex](input, output);
}

/// Returns the number of scan variants.
inline int getScanVariantCount() {
    return kScanVariantCount;
}

/// Returns the name of a scan variant by index.
inline const char* getScanVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kScanVariantCount)
        return "Unknown";
    return kScanVariants[variantIndex].name;
}

} // namespace cut
