// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct MatMulQ8VariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kMatMulQ8VariantCount = 1;
inline constexpr int kMatMulQ8DefaultVariant = 0;

inline constexpr MatMulQ8VariantInfo kMatMulQ8Variants[kMatMulQ8VariantCount] = {
    {"MatMulQ8T16R4x4", 16, 16, 64, 64, "Q8 T16 R4x4"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledMatMulQ8T16R4x4(DataType input1, DataType output);

using CompiledMatMulQ8Fn = std::optional<std::vector<uint32_t>> (*)(DataType, DataType);

inline const CompiledMatMulQ8Fn kMatMulQ8CompiledFns[kMatMulQ8VariantCount] = {
    compiledMatMulQ8T16R4x4,
};

/// Returns compiled SPIR-V for a matmulq8 variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledMatMulQ8(int variantIndex, DataType input1 = DataType::Float32, DataType output = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kMatMulQ8VariantCount)
        return std::nullopt;
    return kMatMulQ8CompiledFns[variantIndex](input1, output);
}

/// Returns the number of matmulq8 variants.
inline int getMatMulQ8VariantCount() {
    return kMatMulQ8VariantCount;
}

/// Returns the name of a matmulq8 variant by index.
inline const char* getMatMulQ8VariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kMatMulQ8VariantCount)
        return "Unknown";
    return kMatMulQ8Variants[variantIndex].name;
}

} // namespace cut
