#include "Dispatcher.h"

#include "OpNode.h"
#include "Shaders.h"
#include <ComputeInterface.h>

#include <cstring>
#include <stdexcept>

namespace cut {

Dispatcher::Dispatcher(ComputeInterface *iface) : iface_(iface) {}

bool Dispatcher::encode(std::unique_ptr<OpNode> node) {
  if (!iface_) {
    throw std::runtime_error("Dispatcher::encode: ComputeInterface is null");
  }

  // Sort with 0 or 1 elements is a no-op (nothing to reorder)
  OperatorEnum op = node->op();
  if ((op == SortBitonic || op == SortRadix) && node->executionSize() <= 1) {
    return false;
  }

  // Multi-pass ops: iterate over sub-operations generated by the OpNode
  if (node->isMultiPass()) {
    const auto &subOps = node->subOperations(*this);
    for (const auto &subOp : subOps) {
      Tensor shader =
          getOrCreateInternalShader(subOp->op(), subOp->shaderDtype());
      auto bindings = subOp->handleBindings();
      auto pushData = subOp->pushConstants();
      dispatchInternal(shader, bindings, subOp->dispatchSize(),
                       DataReference(pushData.data(), pushData.size()));
      if (subOp->needsBarrierAfter()) {
        encodeBarrier();
      }
    }
    releaseTempBuffers();
    return true;
  }

  // Dim-reduce ops need internal shader lookup with spec constant patching
  if (node->isDimReduce()) {
    Tensor dimShader = getOrCreateDimReduceShader(
        node->baseReduceOp(), node->shaderDtype(), node->spec());
    auto bindings = node->handleBindings();
    auto pushData = node->pushConstants();
    ComputeDispatch dispatch(dimShader, node->dispatchSize(), bindings);
    dispatch.bindData(DataReference(pushData.data(), pushData.size()),
                      static_cast<uint32_t>(bindings.size()));
    iface_->encode(std::move(dispatch));
    return true;
  }

  // Standard single-dispatch ops: resolve shader here
  Tensor shader =
      getOrCreateShader(node->op(), node->shaderDtype(), node->spec());
  auto bindings = node->handleBindings();
  auto pushData = node->pushConstants();
  ComputeDispatch dispatch(shader, node->dispatchSize(), bindings);
  dispatch.bindData(DataReference(pushData.data(), pushData.size()),
                    static_cast<uint32_t>(bindings.size()));
  iface_->encode(std::move(dispatch));
  return true;
}

Tensor Dispatcher::acquireTempBuffer(size_t numElements, DataType dtype) {
  // Calculate aligned size in bytes for pool lookup
  size_t sizeBytes = ComputeBuffer::calculateAlignedSize(
      {static_cast<uint32_t>(numElements)}, dtype);

  // Iterate pool to find a buffer of sufficient size
  for (auto it = tempBufferPool_.begin(); it != tempBufferPool_.end(); ++it) {
    const auto &buffer = iface_->getBuffer(*it);
    if (buffer.size() >= sizeBytes) {
      Tensor handle = *it;
      tempBufferPool_.erase(it);
      activeTempBuffers_.push_back(handle);
      return handle;
    }
  }

  // No pooled buffer available — create a new one
  Tensor handle =
      iface_->createBuffer({static_cast<uint32_t>(numElements)}, dtype);
  activeTempBuffers_.push_back(handle);
  return handle;
}

void Dispatcher::releaseTempBuffers() {
  for (const auto &handle : activeTempBuffers_) {
    tempBufferPool_.push_back(handle);
  }
  activeTempBuffers_.clear();
}

void Dispatcher::encodeBarrier() {
  iface_->encode(ComputeDispatch::createBarrier());
}

void Dispatcher::dispatchInternal(const Tensor &shader,
                                  const std::vector<ComputeBinding> &bindings,
                                  ThreadSize threadSize,
                                  const DataReference &pushData) {
  ComputeDispatch dispatch(shader, threadSize, bindings);
  dispatch.bindData(pushData, static_cast<uint32_t>(bindings.size()));
  iface_->encode(std::move(dispatch));
}

Tensor Dispatcher::getOrCreateInternalShader(OperatorEnum op, DataType dtype) {
  size_t key = static_cast<size_t>(op) | (static_cast<size_t>(dtype) << 16) |
               (size_t(1) << 48);

  auto it = internalShaderCache_.find(key);
  if (it != internalShaderCache_.end()) {
    return it->second;
  }

  // Compile via the shader generation system
  auto spirv = getShader(op, dtype);
  Tensor handle = iface_->createShaderModule(spirv);
  internalShaderCache_[key] = handle;
  return handle;
}

Tensor Dispatcher::getOrCreateShader(OperatorEnum op,
                                     DataType dtype,
                                     std::optional<uint32_t> spec) {
  // Use (3 << 48) prefix to distinguish from internal/dim-reduce shaders
  size_t key = static_cast<size_t>(op) | (static_cast<size_t>(dtype) << 16) |
               (size_t(3) << 48) |
               (static_cast<size_t>(spec.value_or(0)) << 32);

  auto it = internalShaderCache_.find(key);
  if (it != internalShaderCache_.end()) {
    return it->second;
  }

  Tensor shader;
  if (spec.has_value()) {
    uint32_t s = spec.value();
    std::optional<std::vector<uint32_t>> spirv;
    switch (op) {
    case MatMul:
      spirv = getCompiledMatMul(s, dtype);
      break;
    case Transpose:
      spirv = getCompiledTranspose(s, dtype);
      break;
    case Conv1D:
      spirv = getCompiledConv1D(s, dtype);
      break;
    case Conv2D:
      spirv = getCompiledConv2D(s, dtype);
      break;
    case MaxPool2D:
      spirv = getCompiledMaxPool2D(s, dtype);
      break;
    case AvgPool2D:
      spirv = getCompiledAvgPool2D(s, dtype);
      break;
    default:
      throw std::runtime_error("No spec support for op " + std::to_string(op));
    }
    if (!spirv.has_value()) {
      throw std::runtime_error("Failed to get spec " + std::to_string(s) +
                               " for op " + std::to_string(op));
    }
    shader = iface_->createShaderModule(spirv.value());
  } else {
    std::vector<uint32_t> spirv = getShader(op, dtype);
    shader = iface_->createShaderModule(spirv);
  }

  internalShaderCache_[key] = shader;
  return shader;
}

Tensor Dispatcher::getOrCreateDimReduceShader(OperatorEnum reduceOp,
                                              DataType dtype,
                                              std::optional<uint32_t> spec) {
  // Use bit 49 to distinguish dim-reduce shaders from global-reduce shaders
  // Include spec in the cache key (bits 32-47)
  size_t key = static_cast<size_t>(reduceOp) |
               (static_cast<size_t>(dtype) << 16) | (size_t(2) << 48) |
               (static_cast<size_t>(spec.value_or(0)) << 32);

  auto it = internalShaderCache_.find(key);
  if (it != internalShaderCache_.end()) {
    return it->second;
  }

  auto spirv = getDimReduceShader(reduceOp, dtype, spec);
  Tensor handle = iface_->createShaderModule(spirv);
  internalShaderCache_[key] = handle;
  return handle;
}

} // namespace cut
