#include "Dispatcher.h"

#include "OpNode.h"
#include "TensorStore.h"
#include <ComputeInterface.h>

#include <stdexcept>

namespace cut {

Dispatcher::Dispatcher(TensorStore *store)
    : store_(store), iface_(store->iface()) {}

bool Dispatcher::encode(std::unique_ptr<OpNode> node) {
  return encode(*node);
}

bool Dispatcher::encode(OpNode &node) {
  if (!iface_) {
    throw std::runtime_error("Dispatcher::encode: ComputeInterface is null");
  }

  // Sort with 0 or 1 elements is a no-op (nothing to reorder)
  OperatorEnum op = node.op();
  if ((op == SortBitonic || op == SortRadix) && node.executionSize() <= 1) {
    return false;
  }

  // Multi-pass ops: iterate over sub-operations generated by the OpNode
  if (node.isMultiPass()) {
    const auto &subOps = node.subOperations();
    for (const auto &subOp : subOps) {
      Tensor shader = getOrCreateShader(*subOp);
      auto bindings = subOp->bindings();
      ComputeDispatch dispatch(shader, subOp->dispatchSize(), bindings);
      dispatch.setLabel(subOp->displayName());
      iface_->encode(std::move(dispatch));
      if (subOp->needsBarrierAfter()) {
        encodeBarrier();
      }
    }
    store_->releaseTempBuffers();
    return true;
  }

  // Single-dispatch ops: node resolves its own shader via shader()
  Tensor shader = getOrCreateShader(node);
  auto bindings = node.bindings();
  ComputeDispatch dispatch(shader, node.dispatchSize(), bindings);
  dispatch.setLabel(node.displayName());
  iface_->encode(std::move(dispatch));
  return true;
}

void Dispatcher::encodeBarrier() {
  iface_->encode(ComputeDispatch::createBarrier());
}

Tensor Dispatcher::getOrCreateShader(const OpNode &node) {
  size_t key = node.shaderKey();
  auto it = shaderCache_.find(key);
  if (it != shaderCache_.end()) {
    return it->second;
  }

  auto spirv = node.shader();
  if (!spirv.has_value())
    throw std::runtime_error("Dispatcher: node returned no shader");
  Tensor handle = iface_->createShaderModule(spirv.value());
  shaderCache_[key] = handle;
  return handle;
}

} // namespace cut
