#include "Dispatcher.h"

#include "OpNode.h"
#include <ComputeInterface.h>

#include <cstring>
#include <stdexcept>

namespace cut {

Dispatcher::Dispatcher(ComputeInterface *iface) : iface_(iface) {}

bool Dispatcher::encode(std::unique_ptr<OpNode> node) {
  if (!iface_) {
    throw std::runtime_error("Dispatcher::encode: ComputeInterface is null");
  }

  // Sort with 0 or 1 elements is a no-op (nothing to reorder)
  OperatorEnum op = node->op();
  if ((op == SortBitonic || op == SortRadix) && node->executionSize() <= 1) {
    return false;
  }

  // Multi-pass ops: iterate over sub-operations generated by the OpNode
  if (node->isMultiPass()) {
    const auto &subOps = node->subOperations(*this);
    for (const auto &subOp : subOps) {
      Tensor shader = getOrCreateShader(*subOp);
      auto bindings = subOp->handleBindings();
      auto pushData = subOp->pushConstants();
      dispatchInternal(shader, bindings, subOp->dispatchSize(),
                       DataReference(pushData.data(), pushData.size()));
      if (subOp->needsBarrierAfter()) {
        encodeBarrier();
      }
    }
    releaseTempBuffers();
    return true;
  }

  // Single-dispatch ops: node resolves its own shader via shader()
  Tensor shader = getOrCreateShader(*node);
  auto bindings = node->handleBindings();
  auto pushData = node->pushConstants();
  ComputeDispatch dispatch(shader, node->dispatchSize(), bindings);
  dispatch.bindData(DataReference(pushData.data(), pushData.size()),
                    static_cast<uint32_t>(bindings.size()));
  iface_->encode(std::move(dispatch));
  return true;
}

Tensor Dispatcher::acquireTempBuffer(size_t numElements, DataType dtype) {
  // Calculate aligned size in bytes for pool lookup
  size_t sizeBytes = ComputeBuffer::calculateAlignedSize(
      {static_cast<uint32_t>(numElements)}, dtype);

  // Iterate pool to find a buffer of sufficient size
  for (auto it = tempBufferPool_.begin(); it != tempBufferPool_.end(); ++it) {
    const auto &buffer = iface_->getBuffer(*it);
    if (buffer.size() >= sizeBytes) {
      Tensor handle = *it;
      tempBufferPool_.erase(it);
      activeTempBuffers_.push_back(handle);
      return handle;
    }
  }

  // No pooled buffer available — create a new one
  Tensor handle =
      iface_->createBuffer({static_cast<uint32_t>(numElements)}, dtype);
  activeTempBuffers_.push_back(handle);
  return handle;
}

void Dispatcher::releaseTempBuffers() {
  for (const auto &handle : activeTempBuffers_) {
    tempBufferPool_.push_back(handle);
  }
  activeTempBuffers_.clear();
}

void Dispatcher::encodeBarrier() {
  iface_->encode(ComputeDispatch::createBarrier());
}

void Dispatcher::dispatchInternal(const Tensor &shader,
                                  const std::vector<ComputeBinding> &bindings,
                                  ThreadSize threadSize,
                                  const DataReference &pushData) {
  ComputeDispatch dispatch(shader, threadSize, bindings);
  dispatch.bindData(pushData, static_cast<uint32_t>(bindings.size()));
  iface_->encode(std::move(dispatch));
}

Tensor Dispatcher::getOrCreateShader(const OpNode &node) {
  size_t key = node.shaderKey();
  auto it = shaderCache_.find(key);
  if (it != shaderCache_.end()) {
    return it->second;
  }

  const auto &spirv = node.shader();
  if (!spirv.has_value())
    throw std::runtime_error("Dispatcher: node returned no shader");
  Tensor handle = iface_->createShaderModule(spirv.value());
  shaderCache_[key] = handle;
  return handle;
}

} // namespace cut
