// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct AvgPool2DVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kAvgPool2DVariantCount = 2;
inline constexpr int kAvgPool2DDefaultVariant = 0;

inline constexpr AvgPool2DVariantInfo kAvgPool2DVariants[kAvgPool2DVariantCount] = {
    {"AvgPool2DNaive", 16, 16, 16, 16, "Naive (global memory)"},
    {"AvgPool2DTiled", 16, 16, 16, 16, "SharedMem input tiled"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledAvgPool2DNaive(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledAvgPool2DTiled(DataType input, DataType output);

using CompiledAvgPool2DFn = std::optional<std::vector<uint32_t>> (*)(DataType, DataType);

inline const CompiledAvgPool2DFn kAvgPool2DCompiledFns[kAvgPool2DVariantCount] = {
    compiledAvgPool2DNaive,
    compiledAvgPool2DTiled,
};

/// Returns compiled SPIR-V for a avgpool2d variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledAvgPool2D(int variantIndex, DataType input = DataType::Float32, DataType output = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kAvgPool2DVariantCount)
        return std::nullopt;
    return kAvgPool2DCompiledFns[variantIndex](input, output);
}

/// Returns the number of avgpool2d variants.
inline int getAvgPool2DVariantCount() {
    return kAvgPool2DVariantCount;
}

/// Returns the name of a avgpool2d variant by index.
inline const char* getAvgPool2DVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kAvgPool2DVariantCount)
        return "Unknown";
    return kAvgPool2DVariants[variantIndex].name;
}

} // namespace cut
