// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct ReduceDimVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kReduceDimVariantCount = 5;
inline constexpr int kReduceDimDefaultVariant = 0;

inline constexpr ReduceDimVariantInfo kReduceDimVariants[kReduceDimVariantCount] = {
    {"ReduceDimNaive", 256, 1, 256, 1, "Naive (serial reduce per thread)"},
    {"ReduceDimShared", 256, 1, 256, 1, "SharedMem parallel reduction"},
    {"ReduceDimVariance", 256, 1, 256, 1, "Single-pass Welford variance"},
    {"ReduceDimRMS", 256, 1, 256, 1, "Single-pass RMS"},
    {"ReduceDimLogSumExp", 256, 1, 256, 1, "Single-pass LogSumExp"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledReduceDimNaive(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledReduceDimShared(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledReduceDimVariance(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledReduceDimRMS(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledReduceDimLogSumExp(DataType input, DataType output);

using CompiledReduceDimFn = std::optional<std::vector<uint32_t>> (*)(DataType, DataType);

inline const CompiledReduceDimFn kReduceDimCompiledFns[kReduceDimVariantCount] = {
    compiledReduceDimNaive,
    compiledReduceDimShared,
    compiledReduceDimVariance,
    compiledReduceDimRMS,
    compiledReduceDimLogSumExp,
};

/// Returns compiled SPIR-V for a reducedim variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledReduceDim(int variantIndex, DataType input = DataType::Float32, DataType output = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kReduceDimVariantCount)
        return std::nullopt;
    return kReduceDimCompiledFns[variantIndex](input, output);
}

/// Returns the number of reducedim variants.
inline int getReduceDimVariantCount() {
    return kReduceDimVariantCount;
}

/// Returns the name of a reducedim variant by index.
inline const char* getReduceDimVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kReduceDimVariantCount)
        return "Unknown";
    return kReduceDimVariants[variantIndex].name;
}

} // namespace cut
