// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct ReduceDimVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kReduceDimVariantCount = 2;
inline constexpr int kReduceDimDefaultVariant = 0;

inline constexpr ReduceDimVariantInfo kReduceDimVariants[kReduceDimVariantCount] = {
    {"ReduceDimNaive", 256, 1, 256, 1, "Naive (serial reduce per thread)"},
    {"ReduceDimShared", 256, 1, 256, 1, "SharedMem parallel reduction"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledReduceDimNaive(DataType datatype);
std::optional<std::vector<uint32_t>> compiledReduceDimShared(DataType datatype);

using CompiledReduceDimFn = std::optional<std::vector<uint32_t>> (*)(DataType);

inline const CompiledReduceDimFn kReduceDimCompiledFns[kReduceDimVariantCount] = {
    compiledReduceDimNaive,
    compiledReduceDimShared,
};

/// Returns compiled SPIR-V for a reducedim variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledReduceDim(int variantIndex, DataType datatype = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kReduceDimVariantCount)
        return std::nullopt;
    return kReduceDimCompiledFns[variantIndex](datatype);
}

/// Returns the number of reducedim variants.
inline int getReduceDimVariantCount() {
    return kReduceDimVariantCount;
}

/// Returns the name of a reducedim variant by index.
inline const char* getReduceDimVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kReduceDimVariantCount)
        return "Unknown";
    return kReduceDimVariants[variantIndex].name;
}

} // namespace cut
