// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <optional>
#include <vector>

namespace cut {

std::optional<std::vector<uint32_t>> compiledBinaryVecVec(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledBinaryVecVecCmp(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledBinaryVecScalar(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledBinaryVecScalarCmp(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledBinaryVecScalarBuf(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledBinaryVecScalarBufCmp(DataType input, DataType output);

} // namespace cut
