"""
Operation definitions for CUT compute interface.

This module contains the operation name to enum mappings and docstrings
used by the compute module.
"""

# Operation name to enum suffix mapping
BINARY_VEC_VEC_OPS = {
    # Arithmetic
    "add": "BinaryVecVecAdd",
    "subtract": "BinaryVecVecSub",
    "multiply": "BinaryVecVecMul",
    "divide": "BinaryVecVecDiv",
    "mod": "BinaryVecVecMod",
    "power": "BinaryVecVecPow",
    "floor_divide": "BinaryVecVecFloorDiv",
    # Comparison
    "equal": "BinaryVecVecEqual",
    "not_equal": "BinaryVecVecNotEqual",
    "less": "BinaryVecVecLess",
    "less_equal": "BinaryVecVecLessEqual",
    "greater": "BinaryVecVecGreater",
    "greater_equal": "BinaryVecVecGreaterEqual",
    # Min/Max
    "minimum": "BinaryVecVecMin",
    "maximum": "BinaryVecVecMax",
    # New binary vec-vec operations
    "bitwise_and": "BinaryVecVecBitwiseAnd",
    "bitwise_or": "BinaryVecVecBitwiseOr",
    "bitwise_xor": "BinaryVecVecBitwiseXor",
    "left_shift": "BinaryVecVecLeftShift",
    "right_shift": "BinaryVecVecRightShift",
    "logical_and": "BinaryVecVecLogicalAnd",
    "logical_or": "BinaryVecVecLogicalOr",
    "logical_xor": "BinaryVecVecLogicalXor",
    "arctan2": "BinaryVecVecAtan2",
    "hypot": "BinaryVecVecHypot",
    "copysign": "BinaryVecVecCopysign",
    "fmod": "BinaryVecVecFmod",
    "logaddexp": "BinaryVecVecLogaddexp",
    "logaddexp2": "BinaryVecVecLogaddexp2",
}

BINARY_VEC_SCALAR_OPS = {
    # Arithmetic
    "add_scalar": "BinaryVecScalarAdd",
    "subtract_scalar": "BinaryVecScalarSub",
    "multiply_scalar": "BinaryVecScalarMul",
    "divide_scalar": "BinaryVecScalarDiv",
    "mod_scalar": "BinaryVecScalarMod",
    "power_scalar": "BinaryVecScalarPow",
    "floor_divide_scalar": "BinaryVecScalarFloorDiv",
    # Comparison
    "equal_scalar": "BinaryVecScalarEqual",
    "not_equal_scalar": "BinaryVecScalarNotEqual",
    "less_scalar": "BinaryVecScalarLess",
    "less_equal_scalar": "BinaryVecScalarLessEqual",
    "greater_scalar": "BinaryVecScalarGreater",
    "greater_equal_scalar": "BinaryVecScalarGreaterEqual",
    # Min/Max
    "minimum_scalar": "BinaryVecScalarMin",
    "maximum_scalar": "BinaryVecScalarMax",
    # New binary vec-scalar operations
    "bitwise_and_scalar": "BinaryVecScalarBitwiseAnd",
    "bitwise_or_scalar": "BinaryVecScalarBitwiseOr",
    "bitwise_xor_scalar": "BinaryVecScalarBitwiseXor",
    "left_shift_scalar": "BinaryVecScalarLeftShift",
    "right_shift_scalar": "BinaryVecScalarRightShift",
    "logical_and_scalar": "BinaryVecScalarLogicalAnd",
    "logical_or_scalar": "BinaryVecScalarLogicalOr",
    "logical_xor_scalar": "BinaryVecScalarLogicalXor",
    "arctan2_scalar": "BinaryVecScalarAtan2",
    "hypot_scalar": "BinaryVecScalarHypot",
    "copysign_scalar": "BinaryVecScalarCopysign",
    "fmod_scalar": "BinaryVecScalarFmod",
    "leaky_relu": "BinaryVecScalarLeakyRelu",
    "prelu": "BinaryVecScalarPrelu",
    "hardshrink": "BinaryVecScalarHardshrink",
    "softshrink": "BinaryVecScalarSoftshrink",
    "logaddexp_scalar": "BinaryVecScalarLogaddexp",
    "logaddexp2_scalar": "BinaryVecScalarLogaddexp2",
}

UNARY_OPS = {
    "negative": "UnaryNeg",
    "abs": "UnaryAbs",
    "sqrt": "UnarySqrt",
    "exp": "UnaryExp",
    "log": "UnaryLog",
    "log2": "UnaryLog2",
    "log10": "UnaryLog10",
    "sin": "UnarySin",
    "cos": "UnaryCos",
    "tan": "UnaryTan",
    "arcsin": "UnaryAsin",
    "arccos": "UnaryAcos",
    "arctan": "UnaryAtan",
    "sinh": "UnarySinh",
    "cosh": "UnaryCosh",
    "tanh": "UnaryTanh",
    "floor": "UnaryFloor",
    "ceil": "UnaryCeil",
    "round": "UnaryRound",
    "sign": "UnarySign",
    "reciprocal": "UnaryReciprocal",
    "square": "UnarySquare",
    # New unary operations
    "expm1": "UnaryExpm1",
    "log1p": "UnaryLog1p",
    "cbrt": "UnaryCbrt",
    "exp2": "UnaryExp2",
    "degrees": "UnaryDegrees",
    "radians": "UnaryRadians",
    "logical_not": "UnaryLogicalNot",
    "invert": "UnaryBitwiseNot",
    "relu": "UnaryRelu",
    "sigmoid": "UnarySigmoid",
    "gelu": "UnaryGelu",
    "silu": "UnarySilu",
    "softplus": "UnarySoftplus",
    "isnan": "UnaryIsNan",
    "isinf": "UnaryIsInf",
    # Extended unary activations
    "relu6": "UnaryRelu6",
    "elu": "UnaryElu",
    "selu": "UnarySelu",
    "celu": "UnaryCelu",
    "mish": "UnaryMish",
    "hardswish": "UnaryHardswish",
    "hardsigmoid": "UnaryHardsigmoid",
    "hardtanh": "UnaryHardtanh",
    "softsign": "UnarySoftsign",
    "logsigmoid": "UnaryLogSigmoid",
    "tanhshrink": "UnaryTanhshrink",
    # Extended unary math
    "rsqrt": "UnaryRsqrt",
    "trunc": "UnaryTrunc",
    "frac": "UnaryFrac",
    "arcsinh": "UnaryAsinh",
    "arccosh": "UnaryAcosh",
    "arctanh": "UnaryAtanh",
    "isfinite": "UnaryIsFinite",
}

# Docstrings for operations
BINARY_VEC_VEC_DOCS = {
    "add": "Add two buffers element-wise.",
    "subtract": "Subtract two buffers element-wise.",
    "multiply": "Multiply two buffers element-wise.",
    "divide": "Divide two buffers element-wise.",
    "mod": "Modulo of two buffers element-wise.",
    "power": "Power of two buffers element-wise.",
    "floor_divide": "Floor division of two buffers element-wise.",
    "equal": "Element-wise equality comparison. Returns 1.0 for True, 0.0 for False.",
    "not_equal": "Element-wise inequality comparison. Returns 1.0 for True, 0.0 for False.",
    "less": "Element-wise less-than comparison. Returns 1.0 for True, 0.0 for False.",
    "less_equal": "Element-wise less-than-or-equal comparison. Returns 1.0 for True, 0.0 for False.",
    "greater": "Element-wise greater-than comparison. Returns 1.0 for True, 0.0 for False.",
    "greater_equal": "Element-wise greater-than-or-equal comparison. Returns 1.0 for True, 0.0 for False.",
    "minimum": "Element-wise minimum of two buffers.",
    "maximum": "Element-wise maximum of two buffers.",
    # New binary vec-vec operations
    "bitwise_and": "Bitwise AND of two buffers element-wise (integers).",
    "bitwise_or": "Bitwise OR of two buffers element-wise (integers).",
    "bitwise_xor": "Bitwise XOR of two buffers element-wise (integers).",
    "left_shift": "Left shift elements of first buffer by second buffer (integers).",
    "right_shift": "Right shift elements of first buffer by second buffer (integers).",
    "logical_and": "Logical AND of two buffers element-wise. Returns 1.0 for True, 0.0 for False.",
    "logical_or": "Logical OR of two buffers element-wise. Returns 1.0 for True, 0.0 for False.",
    "logical_xor": "Logical XOR of two buffers element-wise. Returns 1.0 for True, 0.0 for False.",
    "arctan2": "Element-wise arc tangent of a/b choosing the quadrant correctly.",
    "hypot": "Element-wise hypotenuse: sqrt(a^2 + b^2).",
    "copysign": "Element-wise copy sign of b to a.",
    "fmod": "Element-wise floating-point remainder of a/b.",
    "logaddexp": "Element-wise log(exp(a) + exp(b)), numerically stable.",
    "logaddexp2": "Element-wise log2(2^a + 2^b), numerically stable.",
}

BINARY_VEC_SCALAR_DOCS = {
    "add_scalar": "Add a scalar to each element of a buffer.",
    "subtract_scalar": "Subtract a scalar from each element of a buffer.",
    "multiply_scalar": "Multiply each element of a buffer by a scalar.",
    "divide_scalar": "Divide each element of a buffer by a scalar.",
    "mod_scalar": "Modulo of each element of a buffer by a scalar.",
    "power_scalar": "Raise each element of a buffer to a scalar power.",
    "floor_divide_scalar": "Floor division of each element of a buffer by a scalar.",
    "equal_scalar": "Element-wise equality comparison with a scalar. Returns 1.0 for True, 0.0 for False.",
    "not_equal_scalar": "Element-wise inequality comparison with a scalar. Returns 1.0 for True, 0.0 for False.",
    "less_scalar": "Element-wise less-than comparison with a scalar. Returns 1.0 for True, 0.0 for False.",
    "less_equal_scalar": "Element-wise less-than-or-equal comparison with a scalar. Returns 1.0 for True, 0.0 for False.",
    "greater_scalar": "Element-wise greater-than comparison with a scalar. Returns 1.0 for True, 0.0 for False.",
    "greater_equal_scalar": "Element-wise greater-than-or-equal comparison with a scalar. Returns 1.0 for True, 0.0 for False.",
    "minimum_scalar": "Element-wise minimum of buffer elements and a scalar.",
    "maximum_scalar": "Element-wise maximum of buffer elements and a scalar.",
    # New binary vec-scalar operations
    "bitwise_and_scalar": "Bitwise AND of buffer elements with a scalar (integers).",
    "bitwise_or_scalar": "Bitwise OR of buffer elements with a scalar (integers).",
    "bitwise_xor_scalar": "Bitwise XOR of buffer elements with a scalar (integers).",
    "left_shift_scalar": "Left shift buffer elements by a scalar amount (integers).",
    "right_shift_scalar": "Right shift buffer elements by a scalar amount (integers).",
    "logical_and_scalar": "Logical AND of buffer elements with a scalar. Returns 1.0 for True, 0.0 for False.",
    "logical_or_scalar": "Logical OR of buffer elements with a scalar. Returns 1.0 for True, 0.0 for False.",
    "logical_xor_scalar": "Logical XOR of buffer elements with a scalar. Returns 1.0 for True, 0.0 for False.",
    "arctan2_scalar": "Element-wise arc tangent of buffer/scalar choosing the quadrant correctly.",
    "hypot_scalar": "Element-wise hypotenuse: sqrt(x^2 + scalar^2).",
    "copysign_scalar": "Element-wise copy sign of scalar to buffer elements.",
    "fmod_scalar": "Element-wise floating-point remainder of buffer/scalar.",
    "leaky_relu": "Leaky ReLU activation: x if x > 0 else alpha * x.",
    "prelu": "PReLU activation: x if x >= 0 else weight * x.",
    "hardshrink": "Hard shrink: x if |x| > lambda else 0.",
    "softshrink": "Soft shrink: sign(x) * max(|x| - lambda, 0).",
    "logaddexp_scalar": "Element-wise log(exp(x) + exp(scalar)), numerically stable.",
    "logaddexp2_scalar": "Element-wise log2(2^x + 2^scalar), numerically stable.",
}

UNARY_DOCS = {
    "negative": "Negate buffer element-wise.",
    "abs": "Absolute value element-wise.",
    "sqrt": "Square root element-wise.",
    "exp": "Exponential element-wise.",
    "log": "Natural logarithm element-wise.",
    "log2": "Base-2 logarithm element-wise.",
    "log10": "Base-10 logarithm element-wise.",
    "sin": "Sine element-wise.",
    "cos": "Cosine element-wise.",
    "tan": "Tangent element-wise.",
    "arcsin": "Inverse sine element-wise.",
    "arccos": "Inverse cosine element-wise.",
    "arctan": "Inverse tangent element-wise.",
    "sinh": "Hyperbolic sine element-wise.",
    "cosh": "Hyperbolic cosine element-wise.",
    "tanh": "Hyperbolic tangent element-wise.",
    "floor": "Floor element-wise.",
    "ceil": "Ceiling element-wise.",
    "round": "Round element-wise.",
    "sign": "Sign element-wise (-1, 0, or 1).",
    "reciprocal": "Reciprocal (1/x) element-wise.",
    "square": "Square (x*x) element-wise.",
    # New unary operations
    "expm1": "Compute exp(x) - 1 element-wise (more accurate for small x).",
    "log1p": "Compute log(1 + x) element-wise (more accurate for small x).",
    "cbrt": "Cube root element-wise.",
    "exp2": "Compute 2^x element-wise.",
    "degrees": "Convert radians to degrees element-wise.",
    "radians": "Convert degrees to radians element-wise.",
    "logical_not": "Logical NOT element-wise. Returns 1.0 for 0, 0.0 otherwise.",
    "invert": "Bitwise NOT (invert) element-wise (integers).",
    "relu": "ReLU activation: max(0, x) element-wise.",
    "sigmoid": "Sigmoid activation: 1/(1+exp(-x)) element-wise.",
    "gelu": "GELU activation element-wise.",
    "silu": "SiLU/Swish activation: x * sigmoid(x) element-wise.",
    "softplus": "Softplus activation: log(1 + exp(x)) element-wise.",
    "isnan": "Check if NaN element-wise. Returns 1.0 for NaN, 0.0 otherwise.",
    "isinf": "Check if infinite element-wise. Returns 1.0 for inf/-inf, 0.0 otherwise.",
    # Extended unary activations
    "relu6": "ReLU6 activation: clamp(x, 0, 6) element-wise.",
    "elu": "ELU activation: x if x >= 0 else exp(x) - 1.",
    "selu": "SELU activation: scale * (x if x >= 0 else alpha * (exp(x) - 1)).",
    "celu": "CELU activation: max(0, x) + min(0, exp(x) - 1).",
    "mish": "Mish activation: x * tanh(softplus(x)).",
    "hardswish": "Hard Swish activation: x * clamp(x + 3, 0, 6) / 6.",
    "hardsigmoid": "Hard Sigmoid activation: clamp(x/6 + 0.5, 0, 1).",
    "hardtanh": "Hard Tanh activation: clamp(x, -1, 1).",
    "softsign": "Softsign activation: x / (1 + |x|).",
    "logsigmoid": "Log Sigmoid activation: -log(1 + exp(-x)).",
    "tanhshrink": "Tanhshrink activation: x - tanh(x).",
    # Extended unary math
    "rsqrt": "Reciprocal square root (1/sqrt(x)) element-wise.",
    "trunc": "Truncate to integer element-wise.",
    "frac": "Fractional part element-wise.",
    "arcsinh": "Inverse hyperbolic sine element-wise.",
    "arccosh": "Inverse hyperbolic cosine element-wise.",
    "arctanh": "Inverse hyperbolic tangent element-wise.",
    "isfinite": "Check if finite element-wise. Returns 1.0 for finite, 0.0 for inf/nan.",
}

# List of all operation names for __all__ exports
ALL_OPERATION_NAMES = (
    list(BINARY_VEC_VEC_OPS.keys()) +
    list(BINARY_VEC_SCALAR_OPS.keys()) +
    list(UNARY_OPS.keys())
)
