// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <optional>
#include <vector>

namespace cut {

std::optional<std::vector<uint32_t>> compiledFusionSiLU(DataType output);
std::optional<std::vector<uint32_t>> compiledFusionBinaryOp(DataType output);

} // namespace cut
