// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct MatMulVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kMatMulVariantCount = 12;
inline constexpr int kMatMulDefaultVariant = 6;

inline constexpr MatMulVariantInfo kMatMulVariants[kMatMulVariantCount] = {
    {"MatMulNaive", 16, 16, 16, 16, "Naive (no tiling)"},
    {"MatMul", 16, 16, 16, 16, "SharedMem 16x16"},
    {"MatMulRegTiled", 16, 16, 64, 64, "RegTiled 4x4"},
    {"MatMulTiled2x2", 16, 16, 32, 32, "T16 R2x2 (4KB)"},
    {"MatMulT8R2x2", 8, 8, 16, 16, "T8 R2x2 (1KB)"},
    {"MatMulT8R4x4", 8, 8, 32, 32, "T8 R4x4 (2KB)"},
    {"MatMulT16R4x4", 16, 16, 64, 64, "T16 R4x4 (8KB)"},
    {"MatMulT16R8x8", 16, 16, 128, 128, "T16 R8x8 (16KB)"},
    {"MatMulT32R2x2", 32, 32, 64, 64, "T32 R2x2 (16KB)"},
    {"MatMulSimdR4x4", 32, 1, 32, 16, "SIMD R4x4 (32x16)"},
    {"MatMulSimdR4x8", 32, 1, 32, 32, "SIMD R4x8 (32x32)"},
    {"MatMulSimdR8x8", 32, 1, 64, 32, "SIMD R8x8 (64x32)"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledMatMulNaive(DataType datatype);
std::optional<std::vector<uint32_t>> compiledMatMul(DataType datatype);
std::optional<std::vector<uint32_t>> compiledMatMulRegTiled(DataType datatype);
std::optional<std::vector<uint32_t>> compiledMatMulTiled2x2(DataType datatype);
std::optional<std::vector<uint32_t>> compiledMatMulT8R2x2(DataType datatype);
std::optional<std::vector<uint32_t>> compiledMatMulT8R4x4(DataType datatype);
std::optional<std::vector<uint32_t>> compiledMatMulT16R4x4(DataType datatype);
std::optional<std::vector<uint32_t>> compiledMatMulT16R8x8(DataType datatype);
std::optional<std::vector<uint32_t>> compiledMatMulT32R2x2(DataType datatype);
std::optional<std::vector<uint32_t>> compiledMatMulSimdR4x4(DataType datatype);
std::optional<std::vector<uint32_t>> compiledMatMulSimdR4x8(DataType datatype);
std::optional<std::vector<uint32_t>> compiledMatMulSimdR8x8(DataType datatype);

using CompiledMatMulFn = std::optional<std::vector<uint32_t>> (*)(DataType);

inline const CompiledMatMulFn kMatMulCompiledFns[kMatMulVariantCount] = {
    compiledMatMulNaive,
    compiledMatMul,
    compiledMatMulRegTiled,
    compiledMatMulTiled2x2,
    compiledMatMulT8R2x2,
    compiledMatMulT8R4x4,
    compiledMatMulT16R4x4,
    compiledMatMulT16R8x8,
    compiledMatMulT32R2x2,
    compiledMatMulSimdR4x4,
    compiledMatMulSimdR4x8,
    compiledMatMulSimdR8x8,
};

/// Returns compiled SPIR-V for a matmul variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledMatMul(int variantIndex, DataType datatype = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kMatMulVariantCount)
        return std::nullopt;
    return kMatMulCompiledFns[variantIndex](datatype);
}

/// Returns the number of matmul variants.
inline int getMatMulVariantCount() {
    return kMatMulVariantCount;
}

/// Returns the name of a matmul variant by index.
inline const char* getMatMulVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kMatMulVariantCount)
        return "Unknown";
    return kMatMulVariants[variantIndex].name;
}

} // namespace cut
