// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct MatMulVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kMatMulVariantCount = 22;
inline constexpr int kMatMulDefaultVariant = 5;

inline constexpr MatMulVariantInfo kMatMulVariants[kMatMulVariantCount] = {
    {"MatMulNaive", 16, 16, 16, 16, "Naive (no tiling)"},
    {"MatMul", 16, 16, 16, 16, "SharedMem 16x16"},
    {"MatMulRegTiled", 16, 16, 64, 64, "RegTiled 4x4"},
    {"MatMulTiled2x2", 16, 16, 32, 32, "T16 R2x2 (4KB)"},
    {"MatMulT8R2x2", 8, 8, 16, 16, "T8 R2x2 (1KB)"},
    {"MatMulT8R4x4", 8, 8, 32, 32, "T8 R4x4 (2KB)"},
    {"MatMulT16R4x4", 16, 16, 64, 64, "T16 R4x4 (8KB)"},
    {"MatMulT16R8x8", 16, 16, 128, 128, "T16 R8x8 (16KB)"},
    {"MatMulT32R2x2", 32, 32, 64, 64, "T32 R2x2 (16KB)"},
    {"MatMulT16R2x8", 16, 16, 32, 128, "T16 R2x8 (10KB)"},
    {"MatMulT16R1x16", 16, 16, 16, 256, "T16 R1x16 (17KB)"},
    {"MatMulSimdR4x4", 32, 1, 32, 16, "SIMD R4x4 (32x16)"},
    {"MatMulSimdR4x8", 32, 1, 32, 32, "SIMD R4x8 (32x32)"},
    {"MatMulSimdR8x8", 32, 1, 64, 32, "SIMD R8x8 (64x32)"},
    {"MatMulVecT16R4x4", 16, 16, 64, 64, "Vec4 T16 R4x4 (8KB)"},
    {"MatMulVecBRegT16R4x4", 16, 16, 64, 64, "Vec4+BReg T16 R4x4 (8KB)"},
    {"MatMulBRegT16R4x4", 16, 16, 64, 64, "BReg T16 R4x4 (8KB)"},
    {"MatMulDblBufT16R4x4", 16, 16, 64, 64, "DblBuf T16 R4x4 (16KB)"},
    {"MatMulLinearT16R4x4", 256, 1, 64, 64, "Linear T16 R4x4 (8KB)"},
    {"MatMulGemv", 32, 1, 1, 4, "GEMV (M=1, K-parallel subgroup reduction)"},
    {"MatMulCoopMat", 32, 1, 16, 16, "CoopMat 16x16 (KHR)"},
    {"MatMulCoopMatTiled", 128, 1, 32, 32, "CoopMat 2x2 Tiled (KHR)"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledMatMulNaive(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMul(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulRegTiled(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulTiled2x2(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulT8R2x2(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulT8R4x4(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulT16R4x4(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulT16R8x8(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulT32R2x2(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulT16R2x8(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulT16R1x16(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulSimdR4x4(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulSimdR4x8(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulSimdR8x8(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulVecT16R4x4(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulVecBRegT16R4x4(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulBRegT16R4x4(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulDblBufT16R4x4(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulLinearT16R4x4(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulGemv(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulCoopMat(DataType input1, DataType input2, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulCoopMatTiled(DataType input1, DataType input2, DataType output);

using CompiledMatMulFn = std::optional<std::vector<uint32_t>> (*)(DataType, DataType, DataType);

inline const CompiledMatMulFn kMatMulCompiledFns[kMatMulVariantCount] = {
    compiledMatMulNaive,
    compiledMatMul,
    compiledMatMulRegTiled,
    compiledMatMulTiled2x2,
    compiledMatMulT8R2x2,
    compiledMatMulT8R4x4,
    compiledMatMulT16R4x4,
    compiledMatMulT16R8x8,
    compiledMatMulT32R2x2,
    compiledMatMulT16R2x8,
    compiledMatMulT16R1x16,
    compiledMatMulSimdR4x4,
    compiledMatMulSimdR4x8,
    compiledMatMulSimdR8x8,
    compiledMatMulVecT16R4x4,
    compiledMatMulVecBRegT16R4x4,
    compiledMatMulBRegT16R4x4,
    compiledMatMulDblBufT16R4x4,
    compiledMatMulLinearT16R4x4,
    compiledMatMulGemv,
    compiledMatMulCoopMat,
    compiledMatMulCoopMatTiled,
};

/// Returns compiled SPIR-V for a matmul variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledMatMul(int variantIndex, DataType input1 = DataType::Float32, DataType input2 = DataType::Float32, DataType output = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kMatMulVariantCount)
        return std::nullopt;
    return kMatMulCompiledFns[variantIndex](input1, input2, output);
}

/// Returns the number of matmul variants.
inline int getMatMulVariantCount() {
    return kMatMulVariantCount;
}

/// Returns the name of a matmul variant by index.
inline const char* getMatMulVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kMatMulVariantCount)
        return "Unknown";
    return kMatMulVariants[variantIndex].name;
}

} // namespace cut
