// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct MatMulQ8VariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kMatMulQ8VariantCount = 8;
inline constexpr int kMatMulQ8DefaultVariant = 2;

inline constexpr MatMulQ8VariantInfo kMatMulQ8Variants[kMatMulQ8VariantCount] = {
    {"MatMulQ8T16R4x4", 16, 16, 64, 64, "Q8 T16 R4x4"},
    {"MatMulQ8Gemv", 256, 1, 1, 256, "Q8 GEMV (M=1 vector)"},
    {"MatMulQ8VecT16R4x4", 16, 16, 64, 64, "Q8 Vec4 T16 R4x4 (cooperative packed loading)"},
    {"MatMulQ8GemvKPar", 32, 1, 1, 4, "Q8 GEMV K-parallel (packed dequant, subgroup reduction)"},
    {"MatMulQ8GemvKPar8", 32, 1, 1, 8, "Q8 GEMV K-parallel 8col (packed dequant, K-unroll x4)"},
    {"MatMulQ8GemvDot", 32, 1, 1, 4, "Q8 GEMV dotPacked4x8EXT (on-the-fly A quantization)"},
    {"MatMulQ8TiledDot", 256, 1, 32, 64, "Q8 TiledDot dotPacked4x8EXT (on-the-fly A quant, int8 shmem B)"},
    {"MatMulQ8CoopMatTiled", 128, 1, 32, 32, "Q8 CoopMat 2x2 Tiled (dequant B→fp16, tensor core)"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledMatMulQ8T16R4x4(DataType input1, DataType scales, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulQ8Gemv(DataType input1, DataType scales, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulQ8VecT16R4x4(DataType input1, DataType scales, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulQ8GemvKPar(DataType input1, DataType scales, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulQ8GemvKPar8(DataType input1, DataType scales, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulQ8GemvDot(DataType input1, DataType scales, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulQ8TiledDot(DataType input1, DataType scales, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulQ8CoopMatTiled(DataType input1, DataType scales, DataType output);

using CompiledMatMulQ8Fn = std::optional<std::vector<uint32_t>> (*)(DataType, DataType, DataType);

inline const CompiledMatMulQ8Fn kMatMulQ8CompiledFns[kMatMulQ8VariantCount] = {
    compiledMatMulQ8T16R4x4,
    compiledMatMulQ8Gemv,
    compiledMatMulQ8VecT16R4x4,
    compiledMatMulQ8GemvKPar,
    compiledMatMulQ8GemvKPar8,
    compiledMatMulQ8GemvDot,
    compiledMatMulQ8TiledDot,
    compiledMatMulQ8CoopMatTiled,
};

/// Returns compiled SPIR-V for a matmulq8 variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledMatMulQ8(int variantIndex, DataType input1 = DataType::Float32, DataType scales = DataType::Float32, DataType output = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kMatMulQ8VariantCount)
        return std::nullopt;
    return kMatMulQ8CompiledFns[variantIndex](input1, scales, output);
}

/// Returns the number of matmulq8 variants.
inline int getMatMulQ8VariantCount() {
    return kMatMulQ8VariantCount;
}

/// Returns the name of a matmulq8 variant by index.
inline const char* getMatMulQ8VariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kMatMulQ8VariantCount)
        return "Unknown";
    return kMatMulQ8Variants[variantIndex].name;
}

} // namespace cut
