// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct MatMulQ4VariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kMatMulQ4VariantCount = 2;
inline constexpr int kMatMulQ4DefaultVariant = 0;

inline constexpr MatMulQ4VariantInfo kMatMulQ4Variants[kMatMulQ4VariantCount] = {
    {"MatMulQ4T16R4x4", 16, 16, 64, 64, "Q4 T16 R4x4"},
    {"MatMulQ4Gemv", 256, 1, 1, 256, "Q4 GEMV (M=1 vector)"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledMatMulQ4T16R4x4(DataType input1, DataType scales, DataType output);
std::optional<std::vector<uint32_t>> compiledMatMulQ4Gemv(DataType input1, DataType scales, DataType output);

using CompiledMatMulQ4Fn = std::optional<std::vector<uint32_t>> (*)(DataType, DataType, DataType);

inline const CompiledMatMulQ4Fn kMatMulQ4CompiledFns[kMatMulQ4VariantCount] = {
    compiledMatMulQ4T16R4x4,
    compiledMatMulQ4Gemv,
};

/// Returns compiled SPIR-V for a matmulq4 variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledMatMulQ4(int variantIndex, DataType input1 = DataType::Float32, DataType scales = DataType::Float32, DataType output = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kMatMulQ4VariantCount)
        return std::nullopt;
    return kMatMulQ4CompiledFns[variantIndex](input1, scales, output);
}

/// Returns the number of matmulq4 variants.
inline int getMatMulQ4VariantCount() {
    return kMatMulQ4VariantCount;
}

/// Returns the name of a matmulq4 variant by index.
inline const char* getMatMulQ4VariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kMatMulQ4VariantCount)
        return "Unknown";
    return kMatMulQ4Variants[variantIndex].name;
}

} // namespace cut
