// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <optional>
#include <vector>

namespace cut {

std::optional<std::vector<uint32_t>> compiledDequantBF16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledDequantQ4K(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledDequantQ5K(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledDequantQ6K(DataType input, DataType output);

} // namespace cut
