// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <optional>
#include <vector>

namespace cut {

std::optional<std::vector<uint32_t>> compiledFill(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledFillUint(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledArange(DataType input, DataType output);

} // namespace cut
