// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct TransposeVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kTransposeVariantCount = 3;
inline constexpr int kTransposeDefaultVariant = 0;

inline constexpr TransposeVariantInfo kTransposeVariants[kTransposeVariantCount] = {
    {"TransposeNaive", 16, 16, 16, 16, "Naive (no shared mem)"},
    {"TransposeTiled16", 16, 16, 16, 16, "SharedMem 16x16"},
    {"TransposeTiled32", 32, 32, 32, 32, "SharedMem 32x32"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledTransposeNaive(DataType datatype);
std::optional<std::vector<uint32_t>> compiledTransposeTiled16(DataType datatype);
std::optional<std::vector<uint32_t>> compiledTransposeTiled32(DataType datatype);

using CompiledTransposeFn = std::optional<std::vector<uint32_t>> (*)(DataType);

inline const CompiledTransposeFn kTransposeCompiledFns[kTransposeVariantCount] = {
    compiledTransposeNaive,
    compiledTransposeTiled16,
    compiledTransposeTiled32,
};

/// Returns compiled SPIR-V for a transpose variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledTranspose(int variantIndex, DataType datatype = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kTransposeVariantCount)
        return std::nullopt;
    return kTransposeCompiledFns[variantIndex](datatype);
}

/// Returns the number of transpose variants.
inline int getTransposeVariantCount() {
    return kTransposeVariantCount;
}

/// Returns the name of a transpose variant by index.
inline const char* getTransposeVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kTransposeVariantCount)
        return "Unknown";
    return kTransposeVariants[variantIndex].name;
}

} // namespace cut
