// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct TransposeVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kTransposeVariantCount = 6;
inline constexpr int kTransposeDefaultVariant = 0;

inline constexpr TransposeVariantInfo kTransposeVariants[kTransposeVariantCount] = {
    {"TransposeNaive", 16, 16, 16, 16, "Naive (no shared mem)"},
    {"TransposeTiled16", 16, 16, 16, 16, "SharedMem 16x16"},
    {"TransposeTiled32", 32, 32, 32, 32, "SharedMem 32x32"},
    {"TransposeTiled16R4", 16, 16, 64, 16, "SharedMem 16x16 RPT=4"},
    {"TransposeTiledVec4", 16, 16, 16, 64, "SharedMem Vec4 16x64"},
    {"TransposeTiledVec4RW", 16, 16, 16, 64, "SharedMem Vec4 R+W 16x64"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledTransposeNaive(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledTransposeTiled16(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledTransposeTiled32(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledTransposeTiled16R4(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledTransposeTiledVec4(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledTransposeTiledVec4RW(DataType input, DataType output);

using CompiledTransposeFn = std::optional<std::vector<uint32_t>> (*)(DataType, DataType);

inline const CompiledTransposeFn kTransposeCompiledFns[kTransposeVariantCount] = {
    compiledTransposeNaive,
    compiledTransposeTiled16,
    compiledTransposeTiled32,
    compiledTransposeTiled16R4,
    compiledTransposeTiledVec4,
    compiledTransposeTiledVec4RW,
};

/// Returns compiled SPIR-V for a transpose variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledTranspose(int variantIndex, DataType input = DataType::Float32, DataType output = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kTransposeVariantCount)
        return std::nullopt;
    return kTransposeCompiledFns[variantIndex](input, output);
}

/// Returns the number of transpose variants.
inline int getTransposeVariantCount() {
    return kTransposeVariantCount;
}

/// Returns the name of a transpose variant by index.
inline const char* getTransposeVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kTransposeVariantCount)
        return "Unknown";
    return kTransposeVariants[variantIndex].name;
}

} // namespace cut
