// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct SoftmaxVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kSoftmaxVariantCount = 4;
inline constexpr int kSoftmaxDefaultVariant = 0;

inline constexpr SoftmaxVariantInfo kSoftmaxVariants[kSoftmaxVariantCount] = {
    {"SoftmaxSoftmax", 256, 1, 1, 1, "Fused single-pass softmax"},
    {"SoftmaxLogSoftmax", 256, 1, 1, 1, "Fused single-pass log-softmax"},
    {"SoftmaxSoftmaxWide", 512, 1, 1, 1, "Fused softmax, 512-thread block (wide rows)"},
    {"SoftmaxLogSoftmaxWide", 512, 1, 1, 1, "Fused log-softmax, 512-thread block (wide rows)"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledSoftmaxSoftmax(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledSoftmaxLogSoftmax(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledSoftmaxSoftmaxWide(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledSoftmaxLogSoftmaxWide(DataType input, DataType output);

using CompiledSoftmaxFn = std::optional<std::vector<uint32_t>> (*)(DataType, DataType);

inline const CompiledSoftmaxFn kSoftmaxCompiledFns[kSoftmaxVariantCount] = {
    compiledSoftmaxSoftmax,
    compiledSoftmaxLogSoftmax,
    compiledSoftmaxSoftmaxWide,
    compiledSoftmaxLogSoftmaxWide,
};

/// Returns compiled SPIR-V for a softmax variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledSoftmax(int variantIndex, DataType input = DataType::Float32, DataType output = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kSoftmaxVariantCount)
        return std::nullopt;
    return kSoftmaxCompiledFns[variantIndex](input, output);
}

/// Returns the number of softmax variants.
inline int getSoftmaxVariantCount() {
    return kSoftmaxVariantCount;
}

/// Returns the name of a softmax variant by index.
inline const char* getSoftmaxVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kSoftmaxVariantCount)
        return "Unknown";
    return kSoftmaxVariants[variantIndex].name;
}

} // namespace cut
