// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct MaxPool2DVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kMaxPool2DVariantCount = 2;
inline constexpr int kMaxPool2DDefaultVariant = 0;

inline constexpr MaxPool2DVariantInfo kMaxPool2DVariants[kMaxPool2DVariantCount] = {
    {"MaxPool2DNaive", 16, 16, 16, 16, "Naive (global memory)"},
    {"MaxPool2DTiled", 16, 16, 16, 16, "SharedMem input tiled"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledMaxPool2DNaive(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledMaxPool2DTiled(DataType input, DataType output);

using CompiledMaxPool2DFn = std::optional<std::vector<uint32_t>> (*)(DataType, DataType);

inline const CompiledMaxPool2DFn kMaxPool2DCompiledFns[kMaxPool2DVariantCount] = {
    compiledMaxPool2DNaive,
    compiledMaxPool2DTiled,
};

/// Returns compiled SPIR-V for a maxpool2d variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledMaxPool2D(int variantIndex, DataType input = DataType::Float32, DataType output = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kMaxPool2DVariantCount)
        return std::nullopt;
    return kMaxPool2DCompiledFns[variantIndex](input, output);
}

/// Returns the number of maxpool2d variants.
inline int getMaxPool2DVariantCount() {
    return kMaxPool2DVariantCount;
}

/// Returns the name of a maxpool2d variant by index.
inline const char* getMaxPool2DVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kMaxPool2DVariantCount)
        return "Unknown";
    return kMaxPool2DVariants[variantIndex].name;
}

} // namespace cut
