#!/usr/bin/env python3
"""Embed transpiled CUDA kernels into CompiledCudaKernels.cpp.

For each supported kernel in the transpiler manifest that has a matching
compiled .spv, computes the normalized SPIR-V hash (identical algorithm to
core/backends/cuda/CudaSpirvKey.cpp) and emits a registry entry mapping that
hash to the kernel's CUDA source. The shared prelude and operator-enum header
are embedded as string constants for NVRTC.

The hash MUST stay in lockstep with cudaNormalizedSpirvHash() in C++.
"""

import argparse
import json
import os
import struct
import sys

FNV_OFFSET = 1469598103934665603
FNV_PRIME = 1099511628211
MASK64 = (1 << 64) - 1

OP_DECORATE = 71
OP_SPEC_CONSTANT = 50
DECORATION_SPEC_ID = 1
HEADER_SIZE = 5


def normalized_spirv_hash(spv_bytes):
    """Mirror of cudaNormalizedSpirvHash: zero spec literals, FNV-1a/64 over LE bytes."""
    if len(spv_bytes) < HEADER_SIZE * 4 or len(spv_bytes) % 4 != 0:
        return None
    words = list(struct.unpack("<%dI" % (len(spv_bytes) // 4), spv_bytes))

    spec_ids = set()
    i = HEADER_SIZE
    n = len(words)
    while i < n:
        wc = words[i] >> 16
        op = words[i] & 0xFFFF
        if wc == 0 or i + wc > n:
            break
        if op == OP_DECORATE and wc >= 4 and words[i + 2] == DECORATION_SPEC_ID:
            spec_ids.add(words[i + 1])
        i += wc

    i = HEADER_SIZE
    while i < n:
        wc = words[i] >> 16
        op = words[i] & 0xFFFF
        if wc == 0 or i + wc > n:
            break
        if op == OP_SPEC_CONSTANT and wc >= 4 and words[i + 2] in spec_ids:
            words[i + 3] = 0
        i += wc

    h = FNV_OFFSET
    for w in words:
        for b in range(4):
            h ^= (w >> (8 * b)) & 0xFF
            h = (h * FNV_PRIME) & MASK64
    return h


_DELIM = "CUTKERNELSRC"


def _raw(s):
    return f'R"{_DELIM}(' + s + f'){_DELIM}"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cu-dir", required=True, help="Transpiled .cu + manifest dir")
    ap.add_argument("--spv-dir", required=True, help="Compiled .spv dir")
    ap.add_argument("--prelude", required=True, help="cut_cuda_prelude.cuh path")
    ap.add_argument("--enums", required=True, help="ComputeOpsShared.h path")
    ap.add_argument("--output", required=True, help="CompiledCudaKernels.cpp path")
    args = ap.parse_args()

    with open(os.path.join(args.cu_dir, "cuda_kernels.json")) as f:
        manifest = json.load(f)

    entries = []  # (hash, source, entry, func)
    seen = {}
    n_skip = 0
    for func, meta in sorted(manifest.items()):
        if not meta.get("supported"):
            continue
        spv = os.path.join(args.spv_dir, func + ".spv")
        cu = os.path.join(args.cu_dir, meta["cu"])
        if not os.path.exists(spv) or not os.path.exists(cu):
            n_skip += 1
            continue
        with open(spv, "rb") as f:
            h = normalized_spirv_hash(f.read())
        if h is None:
            n_skip += 1
            continue
        if h in seen:
            # Distinct kernels must not collide; first wins, warn.
            print(f"WARNING: hash collision {func} vs {seen[h]}", file=sys.stderr)
            continue
        seen[h] = func
        with open(cu) as f:
            src = f.read()
        entries.append((h, src, meta["entry"], func))

    with open(args.prelude) as f:
        prelude = f.read()
    with open(args.enums) as f:
        enums = f.read()

    out = []
    out.append("// Auto-generated by embed_cuda_kernels.py — do not edit")
    out.append('#include <CudaKernelRegistry.h>')
    out.append("")
    out.append("namespace cut {")
    out.append("")
    out.append(f"static const char *kCudaPrelude = {_raw(prelude)};")
    out.append("")
    out.append(f"static const char *kCudaEnums = {_raw(enums)};")
    out.append("")
    out.append(f"static const CudaKernelEntry kEntries[] = {{")
    for h, src, entry, func in entries:
        out.append(f"  // {func}")
        out.append(f'  {{ {h}ULL, {_raw(src)}, "{entry}" }},')
    out.append("};")
    out.append("")
    out.append("static const size_t kEntryCount = "
               "sizeof(kEntries) / sizeof(kEntries[0]);")
    out.append("")
    out.append("const CudaKernelEntry *lookupCudaKernelByHash(uint64_t hash) {")
    out.append("  for (size_t i = 0; i < kEntryCount; ++i) {")
    out.append("    if (kEntries[i].hash == hash) return &kEntries[i];")
    out.append("  }")
    out.append("  return nullptr;")
    out.append("}")
    out.append("")
    out.append("size_t cudaKernelCount() { return kEntryCount; }")
    out.append("const char *cudaPreludeSource() { return kCudaPrelude; }")
    out.append("const char *cudaEnumsSource() { return kCudaEnums; }")
    out.append("")
    out.append("} // namespace cut")
    out.append("")

    with open(args.output, "w") as f:
        f.write("\n".join(out))

    print(f"Embedded {len(entries)} CUDA kernel(s), skipped {n_skip}.")


if __name__ == "__main__":
    main()
