#!/usr/bin/env python3
"""Generic shader variant generator.

Scans subdirectories of --impl-dir for shaders.json files and produces:

For "type": "variants" groups (e.g. matmul):
  1. Concrete .shader files from templates (one per variant)
  2. {Group}Variants.generated.h with dispatch table and lookup functions

For "type": "shaders" groups (simple shader listings):
  1. {Group}Shaders.generated.h with forward declarations for compiled functions
"""

import argparse
import json
import os
import sys


# =============================================================================
# Variant group processing (matmul-style)
# =============================================================================

def generate_variant_shaders(config, group_dir):
    """Generate .shader files by substituting defines into templates."""
    template_dir = os.path.join(group_dir, "templates")

    for variant in config["variants"]:
        template_name = variant["template"] + ".template"
        template_path = os.path.join(template_dir, template_name)

        if not os.path.exists(template_path):
            print(f"ERROR: Template not found: {template_path}", file=sys.stderr)
            sys.exit(1)

        with open(template_path, "r") as f:
            content = f.read()

        # Substitute %KEY% placeholders with define values
        for key, value in variant.get("defines", {}).items():
            content = content.replace(f"%{key}%", str(value))

        shader_path = os.path.join(group_dir, variant["name"] + ".shader")

        # Only write if changed
        if os.path.exists(shader_path):
            with open(shader_path, "r") as f:
                if f.read() == content:
                    continue

        with open(shader_path, "w") as f:
            f.write(content)

        print(f"  Generated {variant['name']}.shader")


def generate_variant_header(config, group_dir, group_name):
    """Generate {Group}Variants.generated.h with dispatch table and functions."""
    variants = config["variants"]
    count = len(variants)

    # Use cpp_prefix if specified, otherwise capitalize directory name
    cap = config.get("cpp_prefix", group_name[0].upper() + group_name[1:])

    # Find default variant index
    default_name = config.get("default_variant", "")
    default_index = -1
    for i, v in enumerate(variants):
        if v["name"] == default_name:
            default_index = i
            break
    if default_index < 0:
        print(f"WARNING: default_variant '{default_name}' not found, using 0",
              file=sys.stderr)
        default_index = 0

    lines = []
    lines.append(f"// Auto-generated by generate_shader_variants.py — do not edit")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <ComputeCommon.h>")
    lines.append("#include <cstdint>")
    lines.append("#include <optional>")
    lines.append("#include <vector>")
    lines.append("")
    lines.append("namespace cut {")
    lines.append("")

    # Variant info struct
    lines.append(f"struct {cap}VariantInfo {{")
    lines.append("    const char* name;")
    lines.append("    uint32_t wgX;")
    lines.append("    uint32_t wgY;")
    lines.append("    uint32_t effTileM;")
    lines.append("    uint32_t effTileN;")
    lines.append("    const char* description;")
    lines.append("};")
    lines.append("")

    # Constants
    lines.append(f"inline constexpr int k{cap}VariantCount = {count};")
    lines.append(f"inline constexpr int k{cap}DefaultVariant = {default_index};")
    lines.append("")

    # Dispatch table
    lines.append(
        f"inline constexpr {cap}VariantInfo "
        f"k{cap}Variants[k{cap}VariantCount] = {{"
    )
    for v in variants:
        wg = v["wg"]
        eff = v["eff_tile"]
        desc = v.get("description", v["name"])
        lines.append(
            f'    {{"{v["name"]}", {wg[0]}, {wg[1]}, '
            f'{eff[0]}, {eff[1]}, "{desc}"}},'
        )
    lines.append("};")
    lines.append("")

    # Forward declarations for compiled shader functions
    lines.append("// Forward declarations (defined in CompiledShaders.cpp)")
    for v in variants:
        lines.append(
            f"std::optional<std::vector<uint32_t>> "
            f"compiled{v['name']}(DataType datatype);"
        )
    lines.append("")

    # Function pointer type and lookup table
    lines.append(
        f"using Compiled{cap}Fn = "
        "std::optional<std::vector<uint32_t>> (*)(DataType);"
    )
    lines.append("")
    lines.append(
        f"inline const Compiled{cap}Fn "
        f"k{cap}CompiledFns[k{cap}VariantCount] = {{"
    )
    for v in variants:
        lines.append(f"    compiled{v['name']},")
    lines.append("};")
    lines.append("")

    # Inline helper functions
    lines.append(f"/// Returns compiled SPIR-V for a {group_name} variant by index.")
    lines.append("inline std::optional<std::vector<uint32_t>>")
    lines.append(
        f"getCompiled{cap}(int variantIndex, "
        "DataType datatype = DataType::Float32) {"
    )
    lines.append(
        f"    if (variantIndex < 0 || variantIndex >= k{cap}VariantCount)"
    )
    lines.append("        return std::nullopt;")
    lines.append(f"    return k{cap}CompiledFns[variantIndex](datatype);")
    lines.append("}")
    lines.append("")

    lines.append(f"/// Returns the number of {group_name} variants.")
    lines.append(f"inline int get{cap}VariantCount() {{")
    lines.append(f"    return k{cap}VariantCount;")
    lines.append("}")
    lines.append("")

    lines.append(f"/// Returns the name of a {group_name} variant by index.")
    lines.append(f"inline const char* get{cap}VariantName(int variantIndex) {{")
    lines.append(
        f"    if (variantIndex < 0 || variantIndex >= k{cap}VariantCount)"
    )
    lines.append('        return "Unknown";')
    lines.append(f"    return k{cap}Variants[variantIndex].name;")
    lines.append("}")
    lines.append("")

    lines.append("} // namespace cut")
    lines.append("")

    header_name = f"{cap}Variants.generated.h"
    header_path = os.path.join(group_dir, header_name)
    content = "\n".join(lines)

    # Only write if changed
    if os.path.exists(header_path):
        with open(header_path, "r") as f:
            if f.read() == content:
                print(f"  {header_name} unchanged")
                return

    with open(header_path, "w") as f:
        f.write(content)
    print(f"  Generated {header_name}")


# =============================================================================
# Simple shader group processing
# =============================================================================

def generate_simple_header(config, group_dir, group_name):
    """Generate {Group}Shaders.generated.h with forward declarations."""
    shaders = config["shaders"]
    cap = group_name[0].upper() + group_name[1:]

    lines = []
    lines.append("// Auto-generated by generate_shader_variants.py — do not edit")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <ComputeCommon.h>")
    lines.append("#include <optional>")
    lines.append("#include <vector>")
    lines.append("")
    lines.append("namespace cut {")
    lines.append("")

    for shader_name in shaders:
        lines.append(
            f"std::optional<std::vector<uint32_t>> "
            f"compiled{shader_name}(DataType datatype = DataType::Float32);"
        )

    lines.append("")
    lines.append("} // namespace cut")
    lines.append("")

    header_name = f"{cap}Shaders.generated.h"
    header_path = os.path.join(group_dir, header_name)
    content = "\n".join(lines)

    # Only write if changed
    if os.path.exists(header_path):
        with open(header_path, "r") as f:
            if f.read() == content:
                print(f"  {header_name} unchanged")
                return

    with open(header_path, "w") as f:
        f.write(content)
    print(f"  Generated {header_name}")


# =============================================================================
# Main
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Generate shader variants and forward-declaration headers"
    )
    parser.add_argument(
        "--impl-dir", required=True,
        help="Root directory containing shader group subdirectories"
    )
    args = parser.parse_args()

    impl_dir = args.impl_dir
    if not os.path.isdir(impl_dir):
        print(f"ERROR: --impl-dir does not exist: {impl_dir}", file=sys.stderr)
        sys.exit(1)

    # Scan subdirectories for shaders.json
    processed = 0
    for entry in sorted(os.listdir(impl_dir)):
        group_dir = os.path.join(impl_dir, entry)
        config_path = os.path.join(group_dir, "shaders.json")

        if not os.path.isdir(group_dir) or not os.path.exists(config_path):
            continue

        with open(config_path, "r") as f:
            config = json.load(f)

        group_type = config.get("type", "shaders")
        group_name = entry

        print(f"Processing group: {group_name} (type={group_type})")

        if group_type == "variants":
            generate_variant_shaders(config, group_dir)
            generate_variant_header(config, group_dir, group_name)
        elif group_type == "shaders":
            generate_simple_header(config, group_dir, group_name)
        else:
            print(f"WARNING: Unknown type '{group_type}' in {config_path}",
                  file=sys.stderr)

        processed += 1

    print(f"Done. Processed {processed} shader group(s).")


if __name__ == "__main__":
    main()
