// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct RMSNormVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kRMSNormVariantCount = 2;
inline constexpr int kRMSNormDefaultVariant = 0;

inline constexpr RMSNormVariantInfo kRMSNormVariants[kRMSNormVariantCount] = {
    {"RMSNormRMSNorm", 256, 1, 1, 1, "Fused RMS normalization"},
    {"RMSNormExtendedRMSNorm", 256, 1, 1, 1, "Fused residual + RMS normalization"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledRMSNormRMSNorm(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledRMSNormExtendedRMSNorm(DataType input, DataType output);

using CompiledRMSNormFn = std::optional<std::vector<uint32_t>> (*)(DataType, DataType);

inline const CompiledRMSNormFn kRMSNormCompiledFns[kRMSNormVariantCount] = {
    compiledRMSNormRMSNorm,
    compiledRMSNormExtendedRMSNorm,
};

/// Returns compiled SPIR-V for a rmsnorm variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledRMSNorm(int variantIndex, DataType input = DataType::Float32, DataType output = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kRMSNormVariantCount)
        return std::nullopt;
    return kRMSNormCompiledFns[variantIndex](input, output);
}

/// Returns the number of rmsnorm variants.
inline int getRMSNormVariantCount() {
    return kRMSNormVariantCount;
}

/// Returns the name of a rmsnorm variant by index.
inline const char* getRMSNormVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kRMSNormVariantCount)
        return "Unknown";
    return kRMSNormVariants[variantIndex].name;
}

} // namespace cut
