// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <cstdint>
#include <optional>
#include <vector>

namespace cut {

struct Conv2DVariantInfo {
    const char* name;
    uint32_t wgX;
    uint32_t wgY;
    uint32_t effTileM;
    uint32_t effTileN;
    const char* description;
};

inline constexpr int kConv2DVariantCount = 2;
inline constexpr int kConv2DDefaultVariant = 0;

inline constexpr Conv2DVariantInfo kConv2DVariants[kConv2DVariantCount] = {
    {"Conv2DNaive", 16, 16, 16, 16, "Naive (global memory)"},
    {"Conv2DTiled", 16, 16, 16, 16, "SharedMem input tiled"},
};

// Forward declarations (defined in CompiledShaders.cpp)
std::optional<std::vector<uint32_t>> compiledConv2DNaive(DataType datatype);
std::optional<std::vector<uint32_t>> compiledConv2DTiled(DataType datatype);

using CompiledConv2DFn = std::optional<std::vector<uint32_t>> (*)(DataType);

inline const CompiledConv2DFn kConv2DCompiledFns[kConv2DVariantCount] = {
    compiledConv2DNaive,
    compiledConv2DTiled,
};

/// Returns compiled SPIR-V for a conv2d variant by index.
inline std::optional<std::vector<uint32_t>>
getCompiledConv2D(int variantIndex, DataType datatype = DataType::Float32) {
    if (variantIndex < 0 || variantIndex >= kConv2DVariantCount)
        return std::nullopt;
    return kConv2DCompiledFns[variantIndex](datatype);
}

/// Returns the number of conv2d variants.
inline int getConv2DVariantCount() {
    return kConv2DVariantCount;
}

/// Returns the name of a conv2d variant by index.
inline const char* getConv2DVariantName(int variantIndex) {
    if (variantIndex < 0 || variantIndex >= kConv2DVariantCount)
        return "Unknown";
    return kConv2DVariants[variantIndex].name;
}

} // namespace cut
