// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <optional>
#include <vector>

namespace cut {

std::optional<std::vector<uint32_t>> compiledBitonicStep(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledBitonicPadInit(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledBitonicCopyBack(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledRadixHistogram(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledRadixScatter(DataType datatype = DataType::Float32);

} // namespace cut
