// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <optional>
#include <vector>

namespace cut {

std::optional<std::vector<uint32_t>> compiledReduce(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledReduceArg(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledReduceDimArg(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledPartialReduce(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledFinalReduce(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledCumOp(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledNorm(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledDot(DataType datatype = DataType::Float32);

} // namespace cut
