// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <optional>
#include <vector>

namespace cut {

std::optional<std::vector<uint32_t>> compiledReduce(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledReduceArg(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledReduceDimArg(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledPartialReduce(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledFinalReduce(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledCumOp(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledNorm(DataType input, DataType output);
std::optional<std::vector<uint32_t>> compiledDot(DataType input, DataType output);

} // namespace cut
