// Auto-generated by generate_shader_variants.py — do not edit
#pragma once

#include <ComputeCommon.h>
#include <optional>
#include <vector>

namespace cut {

std::optional<std::vector<uint32_t>> compiledConv1D(DataType datatype = DataType::Float32);
std::optional<std::vector<uint32_t>> compiledConv2D(DataType datatype = DataType::Float32);

} // namespace cut
